import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { PROFILE_DIR } from './profile.js'
import { getModeDefinition } from '../modes/definitions.js'
import type { MissionPlan, SituationGraph } from '../types.js'

function missionId(): string {
  return `mission-${Date.now().toString(36)}`
}

function buildPhases(goal: string, situation: SituationGraph): MissionPlan['phases'] {
  const mode = situation.suggestedMode
  const phases: MissionPlan['phases'] = []

  phases.push({
    name: 'Understand',
    tasks: [
      `Run \`om sense\` and confirm mode (${mode})`,
      `Review context pack at .openmangos/context-pack.md`,
      `Clarify scope: ${goal}`,
    ],
  })

  if (mode === 'debug' || goal.match(/fix|bug|fail|error/i)) {
    phases.push({
      name: 'Reproduce',
      tasks: [
        'Reproduce the failure with minimal steps',
        'Run `om verify --dry-run` and execute relevant checks',
        'Collect logs (docker compose logs / app logs)',
      ],
    })
  }

  if (mode === 'infra' || situation.infra.length > 0) {
    phases.push({
      name: 'Plan infra changes',
      tasks: [
        'Run plan/diff before any apply (terraform plan, kubectl diff)',
        'Confirm guardrails: no destructive ops without approval',
        'Document rollback steps',
      ],
    })
  }

  phases.push({
    name: 'Implement',
    tasks: [
      'Make minimal focused changes',
      'Match existing code style and patterns',
      `Stay within ${getModeDefinition(mode).label} mode affordances`,
    ],
  })

  phases.push({
    name: 'Validate',
    tasks: [
      'Run `om verify` — all steps must pass',
      'Manual smoke test if UI/runtime affected',
      'Update CHANGELOG if shipping',
    ],
  })

  if (mode === 'ship' || goal.match(/deploy|release|ship/i)) {
    phases.push({
      name: 'Ship',
      tasks: [
        'Version bump + changelog',
        'Deploy via stack-appropriate command (vercel/fly/docker)',
        'Post-deploy health check',
      ],
    })
  }

  return phases
}

export function buildMissionPlan(goal: string, situation: SituationGraph): MissionPlan {
  return {
    id: missionId(),
    goal,
    createdAt: new Date().toISOString(),
    mode: situation.suggestedMode,
    stack: situation.stack,
    phases: buildPhases(goal, situation),
    verification: ['om verify', 'om sense'],
  }
}

export function missionToMarkdown(plan: MissionPlan): string {
  const lines = [
    `# Mission: ${plan.goal}`,
    '',
    `**ID:** ${plan.id}`,
    `**Created:** ${plan.createdAt}`,
    `**Mode:** ${plan.mode}`,
    `**Stack:** ${plan.stack.join(', ') || 'unknown'}`,
    '',
    '---',
    '',
  ]

  for (const phase of plan.phases) {
    lines.push(`## Phase: ${phase.name}`, '')
    for (const task of phase.tasks) {
      lines.push(`- [ ] ${task}`)
    }
    lines.push('')
  }

  lines.push('## Verification', '')
  for (const v of plan.verification) {
    lines.push(`- [ ] \`${v}\``)
  }
  lines.push('')
  lines.push('*Generated by OpenMangos `om mission plan`. Check off tasks as you go.*')
  return lines.join('\n')
}

export async function saveMissionPlan(root: string, plan: MissionPlan): Promise<string> {
  const dir = join(root, PROFILE_DIR, 'mission')
  await mkdir(dir, { recursive: true })
  const path = join(dir, 'plan.md')
  await writeFile(path, missionToMarkdown(plan), 'utf8')
  const jsonPath = join(dir, 'plan.json')
  await writeFile(jsonPath, JSON.stringify(plan, null, 2), 'utf8')
  return path
}